<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WPF_MVVM_SPA_Template</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Client.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Client.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastReport.Data.Json" Version="2026.2.1" />
    <PackageReference Include="FastReport.OpenSource" Version="2026.2.1" />
    <PackageReference Include="FastReport.OpenSource.Export.PdfSimple" Version="2026.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OxyPlot.Core" Version="2.2.0" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DLL_AbrilVilalta_MosiesCuartero\DLL_AbrilVilalta_MosiesCuartero.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Report_clients.frx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
